language: python
python:
    - "3.4"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    - "pip install -r requirements.txt"
    - "pip install selenium"
script:
    - "python manage.py test lists"
    - "python manage.py test accounts"
    - "python manage.py test functional_tests"
    - "phantomjs superlists/static/tests/runner.js lists/static/tests/tests.html"
    - "phantomjs superlists/static/tests/runner.js accounts/static/tests/tests.html"
